name: Gerar APK

on:
  workflow_dispatch:
  push:
    branches:
      - principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Preparar projeto
        run: |
          mkdir projeto
          unzip -q alem-das-apostas-v02-android.zip -d projeto

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.7'

      - name: Compilar APK
        run: |
          cd projeto
          gradle assembleDebug

      - name: Disponibilizar APK
        uses: actions/upload-artifact@v4
        with:
          name: alem-das-apostas-apk
          path: projeto/app/build/outputs/apk/debug/app-debug.apk
